[green_agent]
image = "ghcr.io/rdi-foundation/tau2-agentbeats:latest"
env = { LOG_LEVEL = "INFO", OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[participants]]
agentbeats_id = "019d7357-63bf-7342-a6c6-178ac0ce62b0"
name = "agent"
env = { LOG_LEVEL = "INFO", AGENT_LLM = "openai/gpt-4.5-mini", OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
domain = "airline"
user_llm = "openai/gpt-4.5-mini"
