[green_agent]
agentbeats_id = "019cf80f-8938-79c0-a221-4c7eadd43e7e"
env = {OPENAI_API_KEY = "${OPENAI_API_KEY}", LOG_LEVEL = "INFO"}

[[participants]]
agentbeats_id = "019d7357-63bf-7342-a6c6-178ac0ce62b0"
name = "asturias"
env = {OPENAI_API_KEY = "${OPENAI_API_KEY}", AGENT_LLM = "openai/gpt-4.5-mini"}

[config]
domain = "corebench_hard"
num_tasks = 3 # Use 72 for all tasks
use_mcp = true
mcp_server_command = ["uv", "run", "mcp", "run", "scenarios/corebench/mcp_server.py"]
keep_traces = true 
use_cache = false
